# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [ ]:
# Import library.
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [ ]:
l1 = [1,2,3,4]    # declare a list l1.
nd1 = np.array(l1)    # convert list l1 to numpy array.
print(nd1)    # print numpy array nd1.

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [ ]:
print(nd2.shape)    # print shape of numpy array (It will return shape as tuple).

print(nd2.size)    # The size of numpy array (Total number of elements in array).

print(nd2.dtype)    # The data-type of elements in the array.

(2, 4)
8
int64


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [ ]:
np.identity(2)    # will return an identity matrix of size 2x2 (as identity matrices are always square matrix).

array([[1., 0.],
       [0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.array()** function



In [ ]:
# we can use the np.matrix as well, but numpy documents says np.matrix will get depreciated and might not work after some time,
# therefore using np.array

# np.matrix is for maximumn 2-dimension whereas np.array is for n-dimensions

d1 = np.array([[9,8,7],[6,5,4],[3,2,1]])
d1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
#we can also use the arange method and then reshape the array into the desired matrix
d2 = np.arange(start = 9, stop = 0, step = -1)
d2 = d2.reshape(3,3)
d2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### Question 3

Interchange both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [ ]:
d1.T    # Return transpose of array d1.

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

### Question 4
Add + 1 to all the elements in the given matrix.

In [ ]:
d1 + 1    # Adds the constant to each element of the array.

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [ ]:
nd6 = np.matrix([[ 1, 4, 9, 121, 144, 169], [ 16, 25, 36, 196, 225, 256], [ 49, 64, 81, 289, 324, 361]])    # declare numpy array

In [ ]:
nd6    # print array.

matrix([[  1,   4,   9, 121, 144, 169],
        [ 16,  25,  36, 196, 225, 256],
        [ 49,  64,  81, 289, 324, 361]])

In [ ]:
nd6.mean()    # Returns mean of the elements of array.

131.66666666666666

### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [ ]:
np.dot(d1, nd6)    # Returns the dot product of d1 and nd6.

matrix([[ 480,  684,  936, 4680, 5364, 6096],
        [ 282,  405,  558, 2862, 3285, 3738],
        [  84,  126,  180, 1044, 1206, 1380]])

### Array Slicing/Indexing:

- Now we'll learn to access multiple elements or a range of elements from an array.

In [ ]:
x = np.arange(20)        # Creates a numpy array with 20 integers from 0 to 19.
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Question 8

Print the array elements from start to 4th position


In [ ]:
x[:5]                  # Returns the first 5 elements of array.

array([0, 1, 2, 3, 4])

### Question 9

- Return elements from first position with step size 2. (Difference between consecutive elements is 2)

In [ ]:
x[1::2]                  # Returns the elements of array from 2nd element to further elements with step size of 2.

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### Question 10

Reverse the array using array indexing:

In [ ]:
x[::-1]               # Returns the reversed array.

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])