# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [34]:

vec4 = np.linspace(0,5,10)
print(vec4)
# print('')
# print(vec4.reshape(5,2))
# vec4_reshaped = vec4.reshape(5,2)
# print(vec4_reshaped)
# print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [36]:
vec1 = np.arange(0, 12)
vec2 = vec1.reshape(4, 3)
print(vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.93576795 0.89538632 0.14829776 0.62584595 0.26220564]
 [0.61318295 0.90514092 0.22339055 0.61843894 0.53668528]
 [0.60727082 0.45613375 0.05633727 0.50784367 0.20313279]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]

[[-0.39795712  0.09334181  0.75089613  1.45520742  0.70320979]
 [ 1.0804369  -0.2376756   0.05487796 -0.2549256   1.2861703 ]
 [ 1.21859548 -1.49141885  0.36741925  0.06878321  0.12998861]
 [ 2.09419318 -0.71847883 -0.28605748  1.34809925  0.60137215]
 [ 1.08843037 -1.47066491  0.64807845 -0.79808518  0.11594896]
 [ 0.15850742  2.65820136  1.70779834 -1.7714296   1.69067977]
 [ 0.2237688   0.81616147  1.41782953  0.69831268 -0.14597582]
 [-1.04751268 -0.86217443 -0.5215332   1.06195007  1.41024605]
 [-1.40390692 -0.43798297 -0.50999804 -0.93786575  1.91184668]
 [ 1.07439831  0.41708901  0.28326535  0.0166288  -0.03752496]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5224436890880162
0.99877703307497


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.056337269654188615
2.658201356950472


In [14]:
# break here for next video!

In [37]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.8419109   0.86487614  0.94360893  0.38131846 -2.10421021  0.0574255
 -1.21211571 -1.38837867  1.27941449  0.6653114  -1.09533597  1.1736936
 -0.68732004 -2.95722679 -1.66348946  0.91463339 -0.20520704 -0.36951323
 -0.59602442]
-1.2121157055930332


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.78649383 -0.42027825 -0.96929558 -0.80635581  0.98935682]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-2.3307588   0.16255178 -0.96929558 -0.03267955  1.95833135]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.93576795 0.89538632 0.14829776 0.62584595 0.26220564]
 [0.61318295 0.90514092 0.22339055 0.61843894 0.53668528]
 [0.60727082 0.45613375 0.05633727 0.50784367 0.20313279]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]
0.22339055471051883
0.22339055471051883


In [19]:
print(rand_mat[0:2,1:3])

[[0.89538632 0.14829776]
 [0.90514092 0.22339055]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-2.3307588  -1.17117874  2.09935173  0.16255178  1.78649383 -0.42027825
 -0.96929558 -0.80635581  0.98935682 -0.03267955  1.12590145 -0.08456372
  1.95833135 -0.17914434  0.90596411 -0.834813    0.47749862 -0.83189416
  0.23960308]

[-2.3307588  -1.17117874  2.09935173  4.          4.         -0.42027825
 -0.96929558 -0.80635581  0.98935682 -0.03267955  1.12590145 -0.08456372
  1.95833135 -0.17914434  0.90596411 -0.834813    0.47749862 -0.83189416
  0.23960308]

[-2.3307588  -1.17117874  2.09935173  1.          2.         -0.42027825
 -0.96929558 -0.80635581  0.98935682 -0.03267955  1.12590145 -0.08456372
  1.95833135 -0.17914434  0.90596411 -0.834813    0.47749862 -0.83189416
  0.23960308]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.93576795 0.89538632 0.14829776 0.62584595 0.26220564]
 [0.61318295 0.90514092 0.22339055 0.61843894 0.53668528]
 [0.60727082 0.45613375 0.05633727 0.50784367 0.20313279]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]

[[0.93576795 0.89538632 0.14829776 0.62584595 0.26220564]
 [0.61318295 0.90514092 0.22339055 0.         0.        ]
 [0.60727082 0.45613375 0.05633727 0.         0.        ]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.93576795 0.89538632 0.14829776]
 [0.61318295 0.90514092 0.22339055]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.62584595 0.26220564]
 [3.         3.         3.         0.         0.        ]
 [0.60727082 0.45613375 0.05633727 0.         0.        ]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.62584595 0.26220564]
 [3.         3.         3.         0.         0.        ]
 [0.60727082 0.45613375 0.05633727 0.         0.        ]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]


In [25]:
# break here for next video

In [40]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print("\n", rand_vec==1)
print("\n",rand_vec[rand_vec==0])
print("\n",rand_vec[rand_vec>0])

[ 1.09392795  0.554759   -1.54169998 -1.52210409  1.23342184  0.34404877
 -0.64052227  1.00358635  0.6015604  -0.52714405  0.11745528  1.24709895
  0.38790612  1.694568   -1.148535  ]
[ True  True False False  True  True False  True  True False  True  True
  True  True False]

 [False False False False False False False False False False False False
 False False False]

 []

 [1.09392795 0.554759   1.23342184 0.34404877 1.00358635 0.6015604
 0.11745528 1.24709895 0.38790612 1.694568  ]


In [42]:
print(rand_mat2)
print("\n", rand_mat2>0)
print("\n",rand_mat2[rand_mat2>0])

[[-0.39795712  0.09334181  0.75089613  1.45520742  0.70320979]
 [ 1.0804369  -0.2376756   0.05487796 -0.2549256   1.2861703 ]
 [ 1.21859548 -1.49141885  0.36741925  0.06878321  0.12998861]
 [ 2.09419318 -0.71847883 -0.28605748  1.34809925  0.60137215]
 [ 1.08843037 -1.47066491  0.64807845 -0.79808518  0.11594896]
 [ 0.15850742  2.65820136  1.70779834 -1.7714296   1.69067977]
 [ 0.2237688   0.81616147  1.41782953  0.69831268 -0.14597582]
 [-1.04751268 -0.86217443 -0.5215332   1.06195007  1.41024605]
 [-1.40390692 -0.43798297 -0.50999804 -0.93786575  1.91184668]
 [ 1.07439831  0.41708901  0.28326535  0.0166288  -0.03752496]]

 [[False  True  True  True  True]
 [ True False  True False  True]
 [ True False  True  True  True]
 [ True False False  True  True]
 [ True False  True False  True]
 [ True  True  True False  True]
 [ True  True  True  True False]
 [False False False  True  True]
 [False False False False  True]
 [ True  True  True  True False]]

 [0.09334181 0.75089613 1.45520742 

In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.64269473  0.15403586  1.17484089  0.80867736  0.05067171  0.65315767
  1.11868591 -0.14497237 -1.01630732  1.23153905  0.81520483  0.64465437
 -0.73175526 -0.80639329 -1.26150919]

[-0.64269473  0.15403586 -5.         -5.          0.05067171 -5.
 -5.         -0.14497237 -1.01630732 -5.         -5.         -5.
 -0.73175526 -0.80639329 -1.26150919]


In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.39795712  0.09334181  0.75089613  1.45520742  0.70320979]
 [ 1.0804369  -0.2376756   0.05487796 -0.2549256   1.2861703 ]
 [ 1.21859548 -1.49141885  0.36741925  0.06878321  0.12998861]
 [ 2.09419318 -0.71847883 -0.28605748  1.34809925  0.60137215]
 [ 1.08843037 -1.47066491  0.64807845 -0.79808518  0.11594896]
 [ 0.15850742  2.65820136  1.70779834 -1.7714296   1.69067977]
 [ 0.2237688   0.81616147  1.41782953  0.69831268 -0.14597582]
 [-1.04751268 -0.86217443 -0.5215332   1.06195007  1.41024605]
 [-1.40390692 -0.43798297 -0.50999804 -0.93786575  1.91184668]
 [ 1.07439831  0.41708901  0.28326535  0.0166288  -0.03752496]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.62584595 0.26220564]
 [3.         3.         3.         0.         0.        ]
 [0.60727082 0.45613375 0.05633727 0.         0.        ]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]

[[-0.39795712  0.09334181  0.75089613  1.45520742  0.70320979]
 [ 1.0804369  -0.2376756   0.05487796 -0.2549256   1.2861703 ]
 [ 1.21859548 -1.49141885  0.36741925  0.06878321  0.12998861]
 [ 2.09419318 -0.71847883 -0.28605748  1.34809925  0.60137215]
 [ 1.08843037 -1.47066491  0.64807845 -0.79808518  0.11594896]
 [ 0.15850742  2.65820136  1.70779834 -1.7714296   1.69067977]
 [ 0.2237688   0.81616147  1.41782953  0.69831268 -0.14597582]
 [-1.04751268 -0.86217443 -0.5215332   1.06195007  1.41024605]
 [-1.40390692 -0.43798297 -0.50999804 -0.93786575  1.91184668]
 [ 1.07439831  0.41708901  0.28326535  0.0166288  -0.03752496]]
[[3.         3.         3.         0.62584595 0.26220564]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.62584595 0.26220564]
 [3.         3.         3.         0.         0.        ]
 [0.60727082 0.45613375 0.05633727 0.         0.        ]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]

[[3.         3.         3.         0.62584595 0.26220564]
 [3.         3.         3.         0.         0.        ]
 [0.60727082 0.45613375 0.05633727 0.         0.        ]
 [0.36629599 0.18441653 0.86459691 0.65401796 0.2978974 ]
 [0.68068218 0.49420557 0.31854839 0.9338812  0.67148952]]
