In [7]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = array1
print(array2)
array2[2,1] = 0

print("\n",array2)

print("\n",array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[1 2 3]
 [4 5 6]
 [7 0 9]]

 [[1 2 3]
 [4 5 6]
 [7 0 9]]


In [9]:
vec = np.arange(10,20)
vec2 = vec[np.arange(0,10,3)]
print(vec2)
print("\n", np.arange(0,10,3))

[10 13 16 19]

 [0 3 6 9]
