In [1]:
a= [1,2,3]

In [2]:
b= a
b[0]=20
a

[20, 2, 3]

In [29]:
c= a[:]
c[0]=30

print(a)
print(c)


[20, 2, 3]
[30, 2, 3]


In [30]:
a= [1,2,3,4,5]
d= list(a)
d[0]=10
print(a)
print(d)

[1, 2, 3, 4, 5]
[10, 2, 3, 4, 5]


In [37]:
%%timeit
l= [x*3 for x in range(101)]
l

18.2 µs ± 1.83 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [31]:
l= [x*2 for x in range(101)]
print(l)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200]


In [17]:
import numpy as np

arr= np.array([x for x in range(101)])
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [24]:
v= [1,2,3,4,5]
v+[8]

[1, 2, 3, 4, 5, 8]

In [40]:
x= np.array([1,2,3,4,5])+3 ## numpy aray can concatinate dirctly for each element but list we have to do bracetaround value
                           ## and it will be added into list
k= v+[6]
print(k)
x

[1, 2, 3, 4, 5, 6]


array([4, 5, 6, 7, 8])

In [26]:
x.strides

(4,)

In [43]:
x.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [9]:
import numpy as np
array = np.arr([[1],[3],[5]])
array

AttributeError: module 'numpy' has no attribute 'arr'

In [3]:
dictionary = {"MARKS": 75, "RANK" : 7}
dictionary

{'MARKS': 75, 'RANK': 7}

In [8]:
matrix = np.array([[1,2],[3,4],[5,6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])