#### Data types

In [1]:
#float
float('100.0')

100.0

In [2]:
#int
int('100.0')

ValueError: invalid literal for int() with base 10: '100.0'

In [3]:
int('100')

100

In [6]:
#bool
print(bool(0))
print(bool(1))

False
True


In [7]:
# string
s = "greatlearning"
s[5:]

'learning'

In [8]:
s[::-1]

'gninraeltaerg'

In [9]:
# lists
list1 = ['hello', 1, 4, 5, "world"]
print(list1)
list1 + [5]

['hello', 1, 4, 5, 'world']


['hello', 1, 4, 5, 'world', 5]

In [10]:
t1 = (2, 3,45,4)
print(t1)
t1 + (4)

(2, 3, 45, 4)


TypeError: can only concatenate tuple (not "int") to tuple

In [12]:
t2=(4,5,6)
t3= (10,11,12)
t1+t2+t3

(2, 3, 45, 4, 4, 5, 6, 10, 11, 12)

In [73]:
#dictionary
k = {"saturday":"greatlearning", "monday":"work"}
k.keys()
k.values()

## b assing to a
y= k

# add a valuue into b 
y['Sunday']= 'Rest'
print("adde value to y and see the a values:  ", k)

# delete that value from a an verify is also changed
del k['Sunday']
print("removed value from k and see changes on y",y)

## add value to be again
y['Sunday']= 'Rest'
y['Friday']= 'Busy'

print("adde value to y and see the a values:  ", k)

# drop value from b and see changes in a
y.pop('Sunday')
y.pop('Friday')
print("removed value from y and see changes on k", k)


adde value to y and see the a values:   {'saturday': 'greatlearning', 'monday': 'work', 'Sunday': 'Rest'}
removed value from k and see changes on y {'saturday': 'greatlearning', 'monday': 'work'}
adde value to y and see the a values:   {'saturday': 'greatlearning', 'monday': 'work', 'Sunday': 'Rest', 'Friday': 'Busy'}
removed value from y and see changes on k {'saturday': 'greatlearning', 'monday': 'work'}


In [74]:
k['Wednesday']= 'meeting'
z= k
z

{'saturday': 'greatlearning', 'monday': 'work', 'Wednesday': 'meeting'}

In [75]:
person1_information = {'city': 'San Francisco', 'name': 'Sam', "food": "shrimps"}
# drop value from dict and see results
print(person1_information.pop("food")) 
person1_information

shrimps


{'city': 'San Francisco', 'name': 'Sam'}

In [51]:
# sets
s1 = set([3,4,4,4,5,6])
s2 = set([4,5,3,3,3,3,4])

In [52]:
s1

{3, 4, 5, 6}

In [53]:
s1 | s2

{3, 4, 5, 6}

In [54]:
s1 & s2

{3, 4, 5}

In [76]:
a = [1,2,3]
a[0]

1

In [78]:
b = a
b[0] = 20
print(a)

[20, 2, 3]


In [81]:
c = a[:]
c[0] = 30
print(a)
print(c)
b

[20, 2, 3]
[30, 2, 3]


[20, 2, 3]

In [84]:
d = list(a)
d[0] = 40
print(a)
print(d)
b

[20, 2, 3]
[40, 2, 3]


[20, 2, 3]

#### Numpy

In [85]:
import numpy as np

In [89]:
l1 = []
for x in range(10):
    l1.append(x*2)

l1

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [90]:
#list comprehension


In [91]:
%%timeit
l1 = [x*2 for x in range(10000)]

664 µs ± 19.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [100]:
arr = np.array([x for x in range(10000)])
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [101]:
arr2 = arr*2
arr2

array([    0,     2,     4, ..., 19994, 19996, 19998])

In [102]:
%%timeit
arr2 = arr*2


8.12 µs ± 73.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


##### broadcasting

In [105]:
# we cant concatenate list with straight forward like below
v1 = [1, 3, 4]
print(type(v1))
v1 + 5

<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [106]:
#  we can concatenate numpy array straight forward like below
np.array([1,2,3]) + 2

array([3, 4, 5])

In [107]:
list1 = [4,5,6,7]
list2 = [1,2,3,4]

In [112]:
# we can loop trhotugh 2 different list elements using by 'zip' function
for i in zip(list1,list2):
    print(i)

(4, 1)
(5, 2)
(6, 3)
(7, 4)


In [115]:
multiplied = []
for item in zip(list1,list2):
    tmp_prod = item[0] * item[1]
    multiplied.append(tmp_prod)
print(multiplied)

[4, 10, 18, 28]


In [116]:
sumof = []
for item in zip(list1,list2):
    tmp_prod = item[0]+item[1]
    sumof.append(tmp_prod)
print(sumof)

[5, 7, 9, 11]


In [129]:
divide = []
for item in zip(list1,list2):
    tmp_prod = item[0]/item[1]
    divide.append(tmp_prod)
print(divide)

[4.0, 2.5, 2.0, 1.75]


In [117]:
list1 = np.array([4,5,6,7])
list2 = np.array([1,2,3,4])
np.multiply(list1, list2)

array([ 4, 10, 18, 28])

In [120]:
np.add(list1, list2)

array([ 5,  7,  9, 11])

In [123]:
np.divide(list1, list2)

array([4.  , 2.5 , 2.  , 1.75])

In [127]:
np.subtract(list1, list2)

array([3, 3, 3, 3])

In [130]:
mat = np.matrix([[1,2,1],[4,5,6],[3,4,5]])
vec = np.array([1,2,3])
np.matmul(mat, vec)

matrix([[ 8, 32, 26]])

In [131]:
invmat = np.array([[0.5, 0.18518519, -0.24074074],
                 [0.5, -0.14814815, 0.09259259],
                 [-0.5, 0.11111111, 0.05555556]])
print(invmat)

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [132]:
np.linalg.inv(invmat)
np.linalg.inv(np.linalg.inv(invmat))

array([[ 0.5       ,  0.18518519, -0.24074074],
       [ 0.5       , -0.14814815,  0.09259259],
       [-0.5       ,  0.11111111,  0.05555556]])

In [143]:
arr = np.arange(12).reshape(3,4)
print(arr)
col_vector = np.array([5,6,7])
print(col_vector)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[5 6 7]


In [144]:
num_cols = arr.shape[1]
print(num_cols)
for col in range(num_cols):
    print(col)
    arr[:, col] += col_vector
    print(arr)

4
0
[[ 5  1  2  3]
 [10  5  6  7]
 [15  9 10 11]]
1
[[ 5  6  2  3]
 [10 11  6  7]
 [15 16 10 11]]
2
[[ 5  6  7  3]
 [10 11 12  7]
 [15 16 17 11]]
3
[[ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]


In [145]:
arr

array([[ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [146]:
arr.strides

(16, 4)

In [150]:
# broadcasting
arr = np.arange(12).reshape(3,4)
add_matrix = np.array([col_vector] * num_cols).T

arr += add_matrix
print(arr)

[[ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]]


In [160]:
np.zeros([5,4,5]) + np.ones([1,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [165]:
np.ones([2,4,4]) + np.zeros([1,4,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])